# Generated by Django 5.0.1 on 2024-02-01 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_backend', '0002_file_user'),
        ('folder_backend', '0005_file_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='folder_backend.folder'),
        ),
    ]
