# Generated by Django 4.2.9 on 2024-02-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_backend', '0004_alter_file_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uid',
            field=models.UUIDField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
