# Generated by Django 4.1.5 on 2024-02-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder_backend', '0009_alter_folder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
    ]
