# Generated by Django 4.1.5 on 2024-02-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder_backend', '0010_alter_folder_user'),
        ('folder_backend', '0010_remove_file_name'),
    ]

    operations = [
    ]
